/**
 * Applies the SQL migrations in `apps/api/drizzle` (generated by `drizzle-kit generate`).
 *
 * Used in two ways: imported by `index.ts` and `testing.ts` to migrate before serving or
 * testing, and runnable directly (`node src/db/migrate.ts`) for a one-off migration.
 * Drizzle records applied migrations in its own `__drizzle_migrations` table, so running
 * it repeatedly is safe.
 *
 * @see apps/api/src/db/README.md
 * @packageDocumentation
 */
import dotenv from 'dotenv';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { fileURLToPath } from 'node:url';
import { createDb } from './client.ts';

dotenv.config({ path: ['.env.local', '../../.env.local'] });

/**
 * Applies all pending SQL migrations from `apps/api/drizzle`.
 * Opens its own short-lived pool and closes it afterwards.
 *
 * @param connectionString - Defaults to `DATABASE_URL`.
 */
export async function runMigrations(connectionString?: string): Promise<void> {
  const { db, close } = createDb(connectionString);
  try {
    await migrate(db, {
      migrationsFolder: fileURLToPath(new URL('../../drizzle', import.meta.url)),
    });
  } finally {
    await close();
  }
}

// CLI mode: only when this file is the entrypoint, not when imported.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await runMigrations();
  console.log('migrations applied');
}
