/**
 * Drizzle schema: the single source of truth for the Postgres tables.
 *
 * Two groups:
 *
 * - **Better Auth tables** (`user`, `session`, `account`, `verification`): shape dictated
 *   by Better Auth; do not rename columns without regenerating with its CLI.
 * - **Contact center domain**: `tenant` → `membership` / `invite` / `queue` / `embed_key`,
 *   and `call` → `call_participant` / `transcript_segment` / `call_event`.
 *
 * Conventions: ids are `text` UUIDs generated in application code (`randomUUID()`),
 * timestamps default to `now()`, and `jsonb` columns (`tenant.settings`, `customer_meta`,
 * `payload`) are typed loosely here and validated with zod at the edge (`TenantSettings`
 * in `@cc/shared`). Child rows cascade on delete except `call.queue_id`, which has no
 * cascade so a queue with history cannot be dropped silently.
 *
 * After editing: `npx drizzle-kit generate` in `apps/api`; migrations apply at boot.
 *
 * @see apps/api/src/db/README.md
 * @packageDocumentation
 */
import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// --- Better Auth tables (shape generated by `npx @better-auth/cli generate`) ---

/** Signed-in people (Google accounts). Referenced by memberships, queue members and participants. */
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

/** Better Auth sessions; the cookie carries `token`. */
export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => [index('session_user_id_idx').on(t.userId)],
);

/** Better Auth OAuth accounts linked to a user (one per provider). */
export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index('account_user_id_idx').on(t.userId)],
);

/** Better Auth short-lived verification values (OAuth state and similar). */
export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index('verification_identifier_idx').on(t.identifier)],
);

// --- Contact center domain ---

/** One contact center. `slug` is unique and derived from the name. */
export const tenant = pgTable('tenant', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  /** `TenantSettings` from @cc/shared */
  settings: jsonb('settings').$type<Record<string, unknown>>().default({}).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

/** User ↔ tenant with a role; one row per pair. */
export const membership = pgTable(
  'membership',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    role: text('role').$type<'agent' | 'supervisor'>().notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [uniqueIndex('membership_user_tenant_uidx').on(t.userId, t.tenantId)],
);

/** Pending or accepted invitation by email; becomes a membership on first sign-in. */
export const invite = pgTable(
  'invite',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    role: text('role').$type<'agent' | 'supervisor'>().notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    acceptedAt: timestamp('accepted_at'),
  },
  (t) => [uniqueIndex('invite_tenant_email_uidx').on(t.tenantId, t.email)],
);

/** Routing target inside a tenant; `key` is what the embed and the router use. */
export const queue = pgTable(
  'queue',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    name: text('name').notNull(),
    /** Routing configuration (`QueueConfig` in `@cc/shared`): algorithm, skills, language. */
    config: jsonb('config').$type<Record<string, unknown>>().default({}).notNull(),
  },
  (t) => [uniqueIndex('queue_tenant_key_uidx').on(t.tenantId, t.key)],
);

/** Skills a user holds within a tenant, with proficiency 1–5 (skills-based routing). */
export const userSkill = pgTable(
  'user_skill',
  {
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    /** Skill key, e.g. `billing` or `lang:de`. */
    skill: text('skill').notNull(),
    /** 1–5, 5 = expert. */
    proficiency: integer('proficiency').notNull(),
  },
  (t) => [primaryKey({ columns: [t.tenantId, t.userId, t.skill] })],
);

/** Which users ring for which queue (composite primary key). */
export const queueMember = pgTable(
  'queue_member',
  {
    queueId: text('queue_id')
      .notNull()
      .references(() => queue.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.queueId, t.userId] })],
);

/** Public key the call button embeds; `allowed_origins` restricts which sites may use it. */
export const embedKey = pgTable('embed_key', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id')
    .notNull()
    .references(() => tenant.id, { onDelete: 'cascade' }),
  publicKey: text('public_key').notNull().unique(),
  label: text('label').notNull(),
  allowedOrigins: text('allowed_origins')
    .array()
    .default(sql`'{}'::text[]`)
    .notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

/**
 * Machine credentials for the public API (`Authorization: Bearer ak_…`). Only the SHA-256
 * of the secret is stored; `prefix` (the first 12 characters) identifies the key in lists.
 * `permissions` is an explicit subset of `Permission` from `@cc/shared`.
 */
export const apiKey = pgTable('api_key', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id')
    .notNull()
    .references(() => tenant.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  prefix: text('prefix').notNull(),
  hash: text('hash').notNull().unique(),
  permissions: jsonb('permissions').$type<string[]>().default([]).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  lastUsedAt: timestamp('last_used_at'),
  revokedAt: timestamp('revoked_at'),
});

/** One customer call = one LiveKit room. `status` is the `CallStatus` state machine. */
export const call = pgTable(
  'call',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    queueId: text('queue_id')
      .notNull()
      .references(() => queue.id),
    roomName: text('room_name').notNull().unique(),
    status: text('status')
      .$type<'ringing' | 'ai' | 'waiting_human' | 'human' | 'ended'>()
      .notNull(),
    // Contact fields (channel-agnostic routing inputs; voice is the only channel today).
    /** How the contact came in; `voice` (WebRTC) for now, `sip` / `chat` / … later. */
    channel: text('channel').default('voice').notNull(),
    /** Routing priority; higher is served first. Set by the queue, never by the customer. */
    priority: integer('priority').default(0).notNull(),
    /** Skill keys the handling agent must have (empty = any queue member). */
    requiredSkills: jsonb('required_skills').$type<string[]>().default([]).notNull(),
    /** Agent to try first (last-agent / sticky routing), if still online and ready. */
    preferredAgentId: text('preferred_agent_id').references(() => user.id, {
      onDelete: 'set null',
    }),
    /** BCP 47 language tag of the customer, when known (language routing). */
    language: text('language'),
    /** When the customer was put on hold (music plays), `null` while not held. */
    heldAt: timestamp('held_at', { withTimezone: true }),
    /** Wrap-up (disposition) code the handling agent picked; see `TenantSettings.dispositions`. */
    dispositionCode: text('disposition_code'),
    /** Recording state machine: `off` → `on` ⇄ `paused` → `off` (pause = PCI-safe gap). */
    recordingState: text('recording_state')
      .$type<'off' | 'on' | 'paused'>()
      .default('off')
      .notNull(),
    /** LiveKit egress id of the running recording segment, `null` while not recording. */
    recordingEgressId: text('recording_egress_id'),
    /** Free-form tags agents attach during or after the call. */
    tags: jsonb('tags').$type<string[]>().default([]).notNull(),
    customerMeta: jsonb('customer_meta').$type<Record<string, unknown>>().default({}).notNull(),
    startedAt: timestamp('started_at').defaultNow().notNull(),
    endedAt: timestamp('ended_at'),
    aiSummary: text('ai_summary'),
  },
  (t) => [index('call_tenant_started_idx').on(t.tenantId, t.startedAt)],
);

/** Everyone who joined the room, with LiveKit identity and join/leave times. */
export const callParticipant = pgTable('call_participant', {
  id: text('id').primaryKey(),
  callId: text('call_id')
    .notNull()
    .references(() => call.id, { onDelete: 'cascade' }),
  kind: text('kind')
    .$type<'customer' | 'ai' | 'human' | 'supervisor' | 'transcriber' | 'media'>()
    .notNull(),
  userId: text('user_id').references(() => user.id),
  identity: text('identity').notNull(),
  joinedAt: timestamp('joined_at').defaultNow().notNull(),
  leftAt: timestamp('left_at'),
});

/** One utterance as reported by the AI worker. */
export const transcriptSegment = pgTable(
  'transcript_segment',
  {
    id: text('id').primaryKey(),
    callId: text('call_id')
      .notNull()
      .references(() => call.id, { onDelete: 'cascade' }),
    speaker: text('speaker').notNull(),
    identity: text('identity').notNull(),
    text: text('text').notNull(),
    startMs: integer('start_ms'),
    endMs: integer('end_ms'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [index('transcript_call_idx').on(t.callId, t.createdAt)],
);

/** Append-only timeline of a call (`call.created`, `offer.accepted`, ...). */
export const callEvent = pgTable(
  'call_event',
  {
    id: text('id').primaryKey(),
    callId: text('call_id')
      .notNull()
      .references(() => call.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().default({}).notNull(),
    at: timestamp('at').defaultNow().notNull(),
  },
  (t) => [index('call_event_call_idx').on(t.callId, t.at)],
);

/**
 * Routing state, part 1: who is online and in which agent state. One row per desk user
 * with an open socket; written by `routing.ts`, owned by the API instance whose sockets
 * the user is on (`instanceId`, refreshed in `lastSeen` by a heartbeat so a crashed
 * instance's users are swept). Timestamps are `timestamptz` because the engine compares
 * them to `Date.now()`.
 */
export const agentPresence = pgTable(
  'agent_presence',
  {
    userId: text('user_id')
      .primaryKey()
      .references(() => user.id, { onDelete: 'cascade' }),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    state: text('state').$type<'ready' | 'not_ready' | 'busy' | 'acw'>().notNull(),
    reason: text('reason'),
    since: timestamp('since', { withTimezone: true }).notNull(),
    callId: text('call_id'),
    acwUntil: timestamp('acw_until', { withTimezone: true }),
    instanceId: text('instance_id').notNull(),
    lastSeen: timestamp('last_seen', { withTimezone: true }).notNull(),
    /** Connection order; the `linear` algorithm rings in this order. */
    seq: serial('seq').notNull(),
    /** Calls handled since connecting (`least_occupied` ordering). */
    handled: integer('handled').default(0).notNull(),
    /** When this agent was last offered a call (`round_robin` ordering). */
    lastOfferedAt: timestamp('last_offered_at', { withTimezone: true }),
  },
  (t) => [index('agent_presence_tenant_idx').on(t.tenantId)],
);

/**
 * Routing state, part 2: one row per call that is ringing. `currentUserId` is the agent
 * being rung until `ringUntil`; `tried` lists who already was. Advanced by the routing
 * tick of whichever API instance gets the row lock first.
 */
export const ringOffer = pgTable('ring_offer', {
  callId: text('call_id')
    .primaryKey()
    .references(() => call.id, { onDelete: 'cascade' }),
  tenantId: text('tenant_id').notNull(),
  queueKey: text('queue_key').notNull(),
  reason: text('reason'),
  summary: text('summary'),
  members: jsonb('members').$type<string[]>().default([]).notNull(),
  tried: jsonb('tried').$type<string[]>().default([]).notNull(),
  currentUserId: text('current_user_id'),
  ringUntil: timestamp('ring_until', { withTimezone: true }),
  giveUpAt: timestamp('give_up_at', { withTimezone: true }),
  ringMs: integer('ring_ms').notNull(),
  /** Human-first: dispatch metadata for the AI when nobody answers (any instance may do it). */
  fallback: jsonb('fallback').$type<Record<string, unknown>>(),
  /** Blind transfer: take the customer off hold as soon as someone accepts. */
  retrieveOnAccept: boolean('retrieve_on_accept').default(false).notNull(),
  /** Selection algorithm of the queue (`RoutingAlgorithm`), frozen at offer time. */
  algorithm: text('algorithm').default('longest_idle').notNull(),
  /** Skill requirements a candidate must meet (`SkillRequirement[]`). */
  skills: jsonb('skills').$type<{ skill: string; min: number }[]>().default([]).notNull(),
  /** Ring this agent first if ready (sticky / last-agent routing). */
  preferredUserId: text('preferred_user_id'),
  /** Call priority (higher first) plus aging when agents are contended. */
  priority: integer('priority').default(0).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
