import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

// --- Better Auth tables (shape generated by `npx @better-auth/cli generate`) ---

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => [index('session_user_id_idx').on(t.userId)],
);

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index('account_user_id_idx').on(t.userId)],
);

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index('verification_identifier_idx').on(t.identifier)],
);

// --- Contact center domain ---

export const tenant = pgTable('tenant', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  /** `TenantSettings` from @cc/shared */
  settings: jsonb('settings').$type<Record<string, unknown>>().default({}).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const membership = pgTable(
  'membership',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    role: text('role').$type<'agent' | 'supervisor'>().notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [uniqueIndex('membership_user_tenant_uidx').on(t.userId, t.tenantId)],
);

export const invite = pgTable(
  'invite',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    role: text('role').$type<'agent' | 'supervisor'>().notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    acceptedAt: timestamp('accepted_at'),
  },
  (t) => [uniqueIndex('invite_tenant_email_uidx').on(t.tenantId, t.email)],
);

export const queue = pgTable(
  'queue',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    name: text('name').notNull(),
  },
  (t) => [uniqueIndex('queue_tenant_key_uidx').on(t.tenantId, t.key)],
);

export const queueMember = pgTable(
  'queue_member',
  {
    queueId: text('queue_id')
      .notNull()
      .references(() => queue.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.queueId, t.userId] })],
);

export const embedKey = pgTable('embed_key', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id')
    .notNull()
    .references(() => tenant.id, { onDelete: 'cascade' }),
  publicKey: text('public_key').notNull().unique(),
  label: text('label').notNull(),
  allowedOrigins: text('allowed_origins')
    .array()
    .default(sql`'{}'::text[]`)
    .notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const call = pgTable(
  'call',
  {
    id: text('id').primaryKey(),
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenant.id, { onDelete: 'cascade' }),
    queueId: text('queue_id')
      .notNull()
      .references(() => queue.id),
    roomName: text('room_name').notNull().unique(),
    status: text('status')
      .$type<'ringing' | 'ai' | 'waiting_human' | 'human' | 'ended'>()
      .notNull(),
    customerMeta: jsonb('customer_meta').$type<Record<string, unknown>>().default({}).notNull(),
    startedAt: timestamp('started_at').defaultNow().notNull(),
    endedAt: timestamp('ended_at'),
    aiSummary: text('ai_summary'),
  },
  (t) => [index('call_tenant_started_idx').on(t.tenantId, t.startedAt)],
);

export const callParticipant = pgTable('call_participant', {
  id: text('id').primaryKey(),
  callId: text('call_id')
    .notNull()
    .references(() => call.id, { onDelete: 'cascade' }),
  kind: text('kind').$type<'customer' | 'ai' | 'human' | 'supervisor' | 'transcriber'>().notNull(),
  userId: text('user_id').references(() => user.id),
  identity: text('identity').notNull(),
  joinedAt: timestamp('joined_at').defaultNow().notNull(),
  leftAt: timestamp('left_at'),
});

export const transcriptSegment = pgTable(
  'transcript_segment',
  {
    id: text('id').primaryKey(),
    callId: text('call_id')
      .notNull()
      .references(() => call.id, { onDelete: 'cascade' }),
    speaker: text('speaker').notNull(),
    identity: text('identity').notNull(),
    text: text('text').notNull(),
    startMs: integer('start_ms'),
    endMs: integer('end_ms'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (t) => [index('transcript_call_idx').on(t.callId, t.createdAt)],
);

export const callEvent = pgTable(
  'call_event',
  {
    id: text('id').primaryKey(),
    callId: text('call_id')
      .notNull()
      .references(() => call.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().default({}).notNull(),
    at: timestamp('at').defaultNow().notNull(),
  },
  (t) => [index('call_event_call_idx').on(t.callId, t.at)],
);
