/**
 * VitePress site rooted at the repository. `srcDir: '.'` means every tracked
 * markdown file is a page: the hand-written guides in `docs/guide`, the generated API
 * reference in `docs/api` (typedoc), and the co-located `README.md` of every app
 * folder, which is how the architecture docs stay next to the code they describe.
 *
 * Mermaid fences (```mermaid) render as diagrams via vitepress-plugin-mermaid.
 */
import { readFileSync } from 'node:fs';
import { type DefaultTheme, defineConfig } from 'vitepress';
import { withMermaid } from 'vitepress-plugin-mermaid';

/** Sidebar generated by typedoc (`npm run docs:api`); empty until it has run. */
const apiSidebar = (() => {
  try {
    return JSON.parse(
      readFileSync('docs/api/typedoc-sidebar.json', 'utf8'),
    ) as DefaultTheme.SidebarItem[];
  } catch {
    return [];
  }
})();

const guide = [
  { text: 'Getting started', link: '/docs/guide/getting-started' },
  { text: 'Architecture', link: '/docs/guide/architecture' },
  { text: 'Call lifecycle', link: '/docs/guide/call-lifecycle' },
  { text: 'Testing', link: '/docs/guide/testing' },
  { text: 'Quality gates', link: '/docs/guide/quality-gates' },
  { text: 'Deployment', link: '/docs/guide/deployment' },
  { text: 'Glossary', link: '/docs/guide/glossary' },
];

/** Co-located architecture READMEs, one per folder that has something to explain. */
const apps = [
  { text: 'Shared contracts', link: '/packages/shared/' },
  {
    text: 'API',
    link: '/apps/api/',
    items: [
      { text: 'Core modules', link: '/apps/api/src/' },
      { text: 'Routes', link: '/apps/api/src/routes/' },
      { text: 'Services', link: '/apps/api/src/services/' },
      { text: 'Database', link: '/apps/api/src/db/' },
    ],
  },
  { text: 'AI agent', link: '/apps/agent/' },
  { text: 'Web desk', link: '/apps/web/' },
  { text: 'Embed button', link: '/apps/embed/' },
  { text: 'Tests', link: '/tests/' },
  { text: 'Build scripts', link: '/build/' },
];

export default withMermaid(
  defineConfig({
    title: 'Contact Center POC',
    description: 'AI-first contact center on LiveKit Cloud — developer documentation',
    base: '/livekit-playground/',
    srcDir: '.',
    srcExclude: [
      '**/node_modules/**',
      '**/dist/**',
      'coverage/**',
      '.agents/**',
      '.claude/**',
      'apps/api/drizzle/**',
      'tests/e2e/report/**',
      'tests/e2e/results/**',
      'CLAUDE.md',
    ],
    outDir: '.vitepress/dist',
    cacheDir: '.vitepress/cache',
    // A folder's README.md becomes its index page, so `/apps/api/` is apps/api/README.md.
    rewrites: { ':path(.*)/README.md': ':path/index.md' },
    cleanUrls: true,
    ignoreDeadLinks: false,
    themeConfig: {
      nav: [
        { text: 'Guide', link: '/docs/' },
        { text: 'Apps', link: '/apps/api/' },
        { text: 'API reference', link: '/docs/api/' },
        { text: 'Repo', link: '/README' },
      ],
      sidebar: {
        '/docs/guide/': [{ text: 'Guide', items: guide }],
        '/docs/api/': [
          { text: 'API reference', items: [{ text: 'Overview', link: '/docs/api/' }] },
          ...apiSidebar,
        ],
        '/': [
          { text: 'Guide', collapsed: true, items: guide },
          { text: 'Apps & packages', items: apps },
          {
            text: 'Repository',
            items: [
              { text: 'README', link: '/README' },
              { text: 'TODO', link: '/TODO' },
              { text: 'AGENTS.md', link: '/AGENTS' },
            ],
          },
        ],
      },
      search: { provider: 'local' },
      socialLinks: [{ icon: 'github', link: 'https://github.com/ggcaponetto/livekit-playground' }],
    },
    mermaid: {},
  }),
);
